version: '3.8'

services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Meta MCP Server (uncomment when ready to deploy)
  # meta-mcp:
  #   build: .
  #   ports:
  #     - "3456:3456"  # MCP server port
  #     - "8080:8080"  # Web UI port
  #   volumes:
  #     - ./config:/app/config
  #     - ./logs:/app/logs
  #     - ./docs:/app/docs
  #   environment:
  #     - QDRANT_URL=http://qdrant:6333
  #   depends_on:
  #     qdrant:
  #       condition: service_healthy
  #   restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
