# Meta MCP Server Configuration for Apple Container
# This configuration assumes Qdrant is running via Apple container framework

server:
  name: "meta-mcp-server"
  host: "localhost"
  port: 3456

web_ui:
  enabled: true
  host: "localhost"
  port: 8080
  auth_enabled: false

strategy:
  primary: "vector"  # Options: vector, llm, rag
  fallback: "vector"
  vector_threshold: 0.75
  max_tools: 10

embeddings:
  # LM Studio configuration (primary)
  lm_studio_endpoint: "http://localhost:1234/v1/embeddings"
  lm_studio_model: "nomic-embed-text-v1.5"

  # Local fallback configuration
  fallback_model: "all-MiniLM-L6-v2"
  batch_size: 32
  cache_dir: "./embedding-models"

vector_store:
  type: "qdrant"
  host: "192.168.64.2"  # Apple container bridge network IP
  port: 6333
  collection_prefix: "meta_mcp"
  # Note: Run ./scripts/get-qdrant-ip.sh to get current IP if it changes

llm:
  endpoint: "http://localhost:1234/v1"
  model: "local-model"
  temperature: 0.3
  max_tokens: 1000

rag:
  chunk_size: 500
  chunk_overlap: 50
  top_k: 5
  score_threshold: 0.7
  include_examples: true

# Child servers are now configured via separate JSON file
# Use --mcp-servers-json flag to specify the MCP servers configuration
  #   command: ["uvx", "@modelcontextprotocol/server-github"]
  #   env:
  #     GITHUB_TOKEN: "${GITHUB_TOKEN}"
  #   documentation: "./docs/tools/github.md"
  #   enabled: true

logging:
  level: "INFO"
  file: "./logs/meta-server.log"
  max_files: 5
  max_size_mb: 10
  console: true
